### ISSUE TITLE
 ERROR  window is not defined

### ISSUE THREAD

**Issue by lohithn4** [MatteoGabriele/vue-gtag#307]
### Description

I just upgraded the module the error has started appearing... unable to figure out what is happening.
### Expected behavior

It should work without any errors.
### Actual behavior

I upgraded my vue-gtag module in my nuxt project. the error started to appear, it appears while running the build and running the app.
 ERROR  window is not defined                                        

  at pageview (node_modules/vue-gtag/dist/vue-gtag.js:292:30)
  at track (node_modules/vue-gtag/dist/vue-gtag.js:475:3)
  at node_modules/vue-gtag/dist/vue-gtag.js:500:7
  at runNextTicks (internal/process/task_queues.js:58:5)
  at listOnTimeout (internal/timers.js:523:9)
  at processTimers (internal/timers.js:497:7)

### Environment

`-- vue-gtag@1.15.0

**Comment by MatteoGabriele** [comment]
I'll have a look at it

**Comment by MatteoGabriele** [comment]
@lohithn4 bug fix on its way. sorry for the issue
